Destiny2Manager.WebApp/Controllers/DestinyController.cs
using Microsoft.AspNetCore.Mvc;
using Destiny2Manager.Models.Bungie;
using Destiny2Manager.Models.Bungie.Constants;
using Pathoschild.Http.Client;
using Newtonsoft.Json;
using System.Data.SQLite;

namespace Destiny2Manager.WebApp.Controllers
{
	public class DestinyController : Controller
	{
		// API Key for making requests to the Destiny 2 API. And a 'client' field for optimization when sending requests.
		public bool AuthenticatedStatus = false;
        private readonly IConfiguration _configuration;

        private readonly FluentClient client;
		
		public DestinyController(IConfiguration configuration) { 
			
			client = new FluentClient(); 
			_configuration = configuration;
		}

		public IActionResult Index()
		{
			return View();
		}

		public async Task<IActionResult> Statistics()
		{
			if (BungieConstants.Auth == null)
			{
				return RedirectToAction("Index", "Home");
			}
			await EstablishUserData();
			return View();
		}
        public async Task GetCharacterEquipmentAsync()
        {
            var apikey = _configuration.GetValue<string>("equipment_key");
            IResponse CharacterEquipmentResponse = await client
            .GetAsync("https://www.bungie.net/Platform/Destiny2/5/Profile/4611686018495570819/Character/2305843009776964460/?components=205")
            .WithOptions(ignoreHttpErrors: true)
            .WithHeader("x-api-key", apikey);
            BungieCharacterEquipmentModel BungieCharacterEquipmentModel = await CharacterEquipmentResponse.As<BungieCharacterEquipmentModel>();
            //  string[] myStrings = new string[0];
            List<string> names = new List<string>();
			List<string> icons = new List<string>();
            foreach (BungieCharacterEquipmentModelItem item in BungieCharacterEquipmentModel.Response.equipment.data.items)
            {
                if (item.itemHash != null)
                {
                    long newId = (long)item.itemHash;
                    bool isSigned = (newId & (1L << 31)) != 0; // check if the integer is signed
                    if (isSigned)
                    {
                        newId = newId - (1L << 32); // convert to signed integer
                    }

                    using (SQLiteConnection connection = new SQLiteConnection("Data Source=X:\\Programming\\VS Projects\\Destiny2Manager\\Destiny2Manager.Models\\Bungie\\Data\\Destiny2Manifest.sqlite3"))
                    {
                        connection.Open();
                        string sql = $"SELECT json FROM DestinyInventoryItemDefinition WHERE id = {newId};";
                        using (SQLiteCommand command = new SQLiteCommand(sql, connection))
                        using (SQLiteDataReader reader = command.ExecuteReader())
                        {
                            if (reader.Read())
                            {
                                string json = reader.GetString(0);

                                dynamic itemData = JsonConvert.DeserializeObject(json);

                                string name = itemData.displayProperties.name;
								string icon = itemData.displayProperties.icon;
                                names.Add(name);
								icons.Add(icon);
								ViewBag.Icons = icons;
                                ViewBag.Names = names;
								string imgurl = "https://www.bungie.net";
                               // Console.WriteLine(name);
                            }
                        }
                    }
                }
            }
        }

        public async Task<IActionResult> Manager()
        {
            if (BungieConstants.Auth == null)
            {
                return RedirectToAction("Index", "Home");
            }
            await GetCharacterEquipmentAsync();
            return View();
        }
        public async void EquipAurvandilAsync()
        {
            BungieEquipItemModel EquipPayload = new BungieEquipItemModel()
            {
                itemId = 6917529859030182000,
                membershipType = 5,
                characterId = 2305843009776964600
            };
            var apikey = _configuration.GetValue<string>("api_key");
            IResponse EquipAurvandil = await client
                .PostAsync("https://www.bungie.net/Platform/Destiny2/Actions/Items/EquipItem/")
                .WithOptions(ignoreHttpErrors: true)
                .WithBearerAuthentication(BungieConstants.Auth.access_token)
                .WithHeader("x-api-key", apikey)
                .WithBody(EquipPayload);
        }

        public async Task<DestinyMembership> EstablishUserData()
		{
			if (BungieConstants.Auth != null)
			{
                var apikey = _configuration.GetValue<string>("api_key");
                IResponse UserDataResponse = await client
				  .GetAsync("https://www.bungie.net/Platform/User/GetCurrentBungieNetUser/")
				  .WithOptions(ignoreHttpErrors: true)
				  .WithHeader("x-api-key", apikey)
				  .WithBearerAuthentication(BungieConstants.Auth.access_token);

				BungieUserModel ResponseDataModel = await UserDataResponse.As<BungieUserModel>();

				IResponse BungieUserMembershipsResponse = await client
				  .GetAsync($"https://www.bungie.net/Platform/User/GetMembershipsById/{ResponseDataModel.Response.membershipId}/5/")
				  .WithOptions(ignoreHttpErrors: true)
				  .WithHeader("x-api-key", apikey)
				  .WithBearerAuthentication(BungieConstants.Auth.access_token);

				BungieUserMembershipsModel MembershipData = await BungieUserMembershipsResponse.As<BungieUserMembershipsModel>();
				DestinyMembership? Membership = MembershipData.Response.destinyMemberships.FirstOrDefault(x => x.membershipType is 3 or 5);
				if (Membership != null)
				{
					IResponse GetHistoricalStatsForAccount = await client
					  .GetAsync($"https://www.bungie.net/Platform/Destiny2/{Membership.membershipType}/Account/{Membership.membershipId}/Stats/")
					  .WithOptions(ignoreHttpErrors: true)
					  .WithHeader("x-api-key", apikey);

					IResponse CharactersDataResponse = await client
					  .GetAsync($"https://www.bungie.net/Platform/Destiny2/{Membership.membershipType}/Profile/{Membership.membershipId}/?components=200")
					  .WithOptions(ignoreHttpErrors: true)
					  .WithHeader("x-api-key", apikey)
					  .WithBearerAuthentication(BungieConstants.Auth.access_token);

					BungieCharacterDataModel CharacterData = await CharactersDataResponse.As<BungieCharacterDataModel>();
					BungieHistoricalStatsModel HistoricalStats = await GetHistoricalStatsForAccount.As<BungieHistoricalStatsModel>();

					// 0 = Titan
					// 1 = Hunter
					// 2 = Warlock
					KeyValuePair<long, CharacterData> WarlockData = CharacterData.Response.characters.data.FirstOrDefault(x => x.Value.classType == 2);
					KeyValuePair<long, CharacterData> HunterData = CharacterData.Response.characters.data.FirstOrDefault(x => x.Value.classType == 1);
					KeyValuePair<long, CharacterData> TitanData = CharacterData.Response.characters.data.FirstOrDefault(x => x.Value.classType == 0);
					BungieEquipItemModel EquipPayload = new BungieEquipItemModel()
					{
						itemId = 6917529859030182332,
						membershipType = Membership.membershipType,
						characterId = Int64.Parse(WarlockData.Value.characterId)

					};
					IResponse GetItemData = await client
					  .GetAsync($"https://www.bungie.net/Platform/Destiny2/5/Profile/{ResponseDataModel.Response.membershipId}/Character/{WarlockData.Value.characterId}/?components=205")
					  .WithOptions(ignoreHttpErrors: true)
					  .WithHeader("x-api-key", apikey);
					BungieItemDataModel ItemData = await GetItemData.As<BungieItemDataModel>();
					double thoursPlayed = 0.0;
					double hhoursPlayed = 0.0;
					double whoursPlayed = 0.0;

					if (GetItemData != null)
					{
						IResponse EquipAurvandil = await client
						  .PostAsync("https://www.bungie.net/Platform/Destiny2/Actions/Items/EquipItem/")
						  .WithOptions(ignoreHttpErrors: true)
						  //   .WithHeader("Content-Type", "application/json")
						  .WithHeader("x-api-key", apikey)
						  .WithBody(EquipPayload)
						  .WithBearerAuthentication(BungieConstants.Auth.access_token);
						//string ChromaRush = $"https://www.bungie.net/{}"
						//ViewData["pee"] = ItemData.Response.equipment.data.items.itemInstanceId;

					}
					if (HistoricalStats != null)
					{
						ViewData["deaths"] = HistoricalStats.Response.mergedAllCharacters.results.allPvE.allTime.deaths.basic.displayValue;

					}
					if (TitanData.Value != null)
					{
						string titanemblembkg = $"https://www.bungie.net{TitanData.Value.emblemBackgroundPath}";
						string titanemblem = $"https://www.bungie.net{TitanData.Value.emblemPath}";
						ViewData["titanemblembkg"] = titanemblembkg;
						ViewData["titanemblem"] = titanemblem;
						int minutesPlayed = int.Parse(TitanData.Value.minutesPlayedTotal);
						thoursPlayed = minutesPlayed / 60.0;
						ViewData["tpt"] = thoursPlayed.ToString("F2");
						ViewData["tll"] = TitanData.Value.light;
					}
					if (HunterData.Value != null)
					{
						string hunteremblembkg = $"https://www.bungie.net{HunterData.Value.emblemBackgroundPath}";
						string hunteremblem = $"https://www.bungie.net{HunterData.Value.emblemPath}";
						ViewData["hunteremblembkg"] = hunteremblembkg;
						ViewData["hunteremblem"] = hunteremblem;
						int minutesPlayed = int.Parse(HunterData.Value.minutesPlayedTotal);
						hhoursPlayed = minutesPlayed / 60.0;
						ViewData["hpt"] = hhoursPlayed.ToString("F2");
						ViewData["hll"] = HunterData.Value.light;

					}
					if (WarlockData.Value != null)
					{

						string warlockemblembkg = $"https://www.bungie.net{WarlockData.Value.emblemBackgroundPath}";
						string warlockemblem = $"https://www.bungie.net{WarlockData.Value.emblemPath}";
						ViewData["wll"] = WarlockData.Value.light;
						int minutesPlayed = int.Parse(WarlockData.Value.minutesPlayedTotal);
						whoursPlayed = minutesPlayed / 60.0;

Destiny2Manager.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta content="width=device-width,initial-scale=1.0,maximum-scale=1.0" name="viewport">

	<!-- Open Graph -->
	<meta property="og:title" content="Your Page Title Here" />
	<meta property="og:url" content="http://dev.thememountain.com/faulkner/project-style-one.html" />
	<meta property="og:type" content="website" />
	<meta property="og:image" content="http://dev.thememountain.com/faulkner/images/portfolio/projects/project-1-1.jpg" />
	<meta property="og:description" content="Your Page Description Here" />

	<!-- Twitter Theme -->
	<meta name="twitter:widgets:theme" content="light">

	<!-- Title &amp; Favicon -->
	<title>@ViewData["Title"] - Destiny2Manager</title>
	<link rel="shortcut icon" type="image/x-icon" href="~/images/theme-mountain-favicon.ico">

	<!-- Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700%7CHind+Madurai:400,500&amp;subset=latin-ext" rel="stylesheet">

	<!-- Css -->
	<link rel="stylesheet" href="~/css/main.css" />
	<link rel="stylesheet" href="~/css/core.min.css" />
	<link rel="stylesheet" href="~/css/skin.css" />

	<!--[if lt IE 9]>
		<script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

</head>
<body>
	@using Destiny2Manager.WebApp.Controllers;
	<!-- Header -->
	<header class="header header-relative header-fixed-on-mobile nav-dark" data-bkg-threshold="100" data-sticky-threshold="0">
		<div class="header-inner">
			<div class="row nav-bar">
				<div class="column width-12 nav-bar-inner">
					<div class="logo">
						<div class="logo-inner">
							<a href="index.html"><img src="~/images/logo-dark.png" alt="Faulkner Logo" /></a>
							<a href="index.html"><img src="~/images/logo.png" alt="Faulkner Logo" /></a>
						</div>
					</div>
					<nav class="navigation nav-block secondary-navigation nav-right">
						<ul>
							<li>
								<!-- Button -->
								<div class="v-align-middle">
																	</div>
							</li>
							<li class="aux-navigation hide">
								<!-- Aux Navigation -->
								<a href="#" class="navigation-show side-nav-show nav-icon">
									<span class="icon-menu"></span>
								</a>
							</li>
						</ul>
					</nav>
					<nav class="navigation nav-block primary-navigation nav-right sub-menu-indicator">
						<ul>
							<li>
								<a asp-area="" asp-controller="Destiny" asp-action="Statistics">Statistics Page</a>
							</li>
							<li>
								<a asp-area="" asp-controller="Destiny" asp-action="Manager">Item Manager</a>
							</li>
							<li>
								<a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
							</li>
							<li>
								<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
							</li>
							<li>
								<a href="shop-grid-three-columns.html">Shop</a>
							</li>
							<li class="contains-mega-sub-menu">
								<a href="elements-accordions.html">Elements</a>
							</li>
							<li>
								<a id="bungieAuth" href="https://www.bungie.net/en/OAuth/Authorize/?client_id=43800&response_type=code" class="button medium pill bkg-charcoal-light bkg-hover-theme color-white color-hover-white">Bungie Authentication</a>
							</li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</header>
	<!-- Header End -->
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>
	<!-- Footer -->
	<footer class="footer footer-light with-border">
		<div class="footer-top">
			<div class="row flex">
				<div class="column width-9">
					<div class="row two-columns-on-tablet">
						<div class="column width-3">
							<div class="widget">
								<h3 class="widget-title mb-30">Product</h3>
								<ul>
									<li><a href="#">About us</a></li>
									<li><a href="#">Careers</a></li>
									<li><a href="#">Press</a></li>
								</ul>
							</div>
						</div>
						<div class="column width-3">
							<div class="widget">
								<h3 class="widget-title mb-30">Company</h3>
								<ul>
									<li><a href="#">Overview</a></li>
									<li><a href="#">Features</a></li>
									<li><a href="#">Pricing</a></li>
								</ul>
							</div>
						</div>
						<div class="column width-3">
							<div class="widget">
								<h3 class="widget-title mb-30">Resources</h3>
								<ul>
									<li><a href="#">News</a></li>
									<li><a href="#">Documentation</a></li>
									<li><a href="#">Faq</a></li>
								</ul>
							</div>
						</div>
						<div class="column width-3">
							<div class="widget">
								<h3 class="widget-title mb-30">Contact</h3>
								<ul>
									<li><a href="#">Email us</a></li>
									<li><a href="#">Tweet Faulkner</a></li>
									<li><a href="#">Visit the office</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="column width-3">
					<div class="widget right left-on-mobile">
						<div class="footer-logo">
							<a href="index.html"><img src="~/" alt="Faulkner Logo" /></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="row">
				<div class="column width-12">
					<div class="footer-bottom-inner">
						<p class="copyright pull-left clear-float-on-mobile">&copy; FuryShiftz. All Rights Reserved.</p> <a href="#" class="scroll-to-top pull-right clear-on-mobile" data-no-hide>Back Top</a>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<script src="~/js/jquery-3.2.1.min.js"></script>
	<script src="~/js/site.js"></script>
	<script src="~/js/timber.min.js"></script>
	<script src="~/js/timber.js"></script>
	<script src="~/js/timber.master.min.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Destiny2Manager.WebApp/Views/Shared/_LayoutEmpty.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Destiny 2 Manager</title>
    <link href="~/images/favicon.png" rel="shortcut icon" type="image/x-icon" />
    <script src="~/js/jquery-3.2.1.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/timber.min.js"></script>
    <script src="~/js/timber.js"></script>
    <script src="~/js/timber.master.min.js"></script>
</head>
<body>
    <div class="content">
        @RenderBody()
    </div>
</body>
</html>